(function(){
 'use strict';
 const main=document.querySelector('main[data-property-id]');if(!main)return;
 const id=main.dataset.propertyId;
 const locale=(value)=>value?.startsWith('es')?'es':value?.startsWith('fr')?'fr-BE':value?.startsWith('de')?'de':value?.startsWith('nl')?'nl':'en';
 let lang;try{lang=locale(new URLSearchParams(location.search).get('lang')||localStorage.getItem('caveHomesLanguageManual')||navigator.language)}catch(_){lang='en'}
 const {labels,types}=window.CHSPropertyUI;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const imageUrl=s=>{if(!s)return '';try{const u=new URL(s,location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch(_){return ''}};
 const concept=imageUrl(main.querySelector('.before-after__after img')?.getAttribute('src')||({'e452d228-d3ed-4d33-9938-12553c0c1b04':'/ai-concepts/casa-cueva-2-benamaurel.webp'}[id]||''));
 let home,images=[],photo=0;
 const price=()=> '€'+Number(home.price||0).toLocaleString({en:'en-GB',es:'es-ES','fr-BE':'fr-BE',de:'de-DE',nl:'nl-NL'}[lang]);
 function savedKeys(){try{return JSON.parse(localStorage.getItem('caveHomesSaved')||'[]')}catch(_){return []}}
 function contactUrl(){const u=new URL('/contact.html',location.origin);u.searchParams.set('property',home.title);u.searchParams.set('property_id',id);u.searchParams.set('lang',lang);return u.pathname+u.search}
 function track(name){window.chsWebsiteEvent?.(name,{property_id:id,property_title:home.title});window.chsTrack?.(name,{property_id:id,language:lang})}
 function gallery(){const w=labels[lang],img=document.getElementById('v16Photo');img.src=images[photo];img.alt=(window.CHSPropertyCopy[id]?.[lang]?.title||home.title)+' — '+w[5]+' '+(photo+1);document.getElementById('v16PhotoCount').textContent=w[5]+' '+(photo+1)+' / '+images.length;document.getElementById('v16Prev').disabled=photo===0;document.getElementById('v16Next').disabled=photo===images.length-1;main.querySelectorAll('.property-thumbs button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===photo)))}
 function render(){
  const w=labels[lang];document.documentElement.lang=lang;
  const entry=window.CHSPropertyCopy[id],same=entry?.source===home.description;
  const copy=same?entry[lang]:null;
  const title=copy?.title||home.title,description=copy?.description||String(home.description||'').replace(/\\n/g,'\n').replace(/\s*Source:\s*tucueva\.com\s*[—-].*$/im,'');
  const type=types[lang][types.en.indexOf(home.property_type)]||home.property_type;
  const facts=[type];if(home.property_type!=='Land'||id.startsWith('27e8d074'))facts.push(Number(home.bedrooms)>0?home.bedrooms+' '+w[11]:w[21]);if(Number(home.bathrooms)>0)facts.push(home.bathrooms+' '+w[12]);if(Number(home.floor_area_m2)>0)facts.push(w[13]+': '+home.floor_area_m2+' m²');if(Number(home.plot_area_m2)>0)facts.push(w[14]+': '+home.plot_area_m2+' m²');
  if(home.property_type!=='Land'){facts.push(home.energy_status==='exempt'?w[19]:/^[A-G]$/.test(home.energy_rating||'')?w[18]+': '+home.energy_rating:w[20])}
  const reserved=home.status==='reserved'||/reserved/i.test(home.title);
  main.innerHTML='<header class="property-brand"><a href="/"><img src="/cave-homes-spain-logo.png" alt="Cave Homes Spain"><span>Cave Homes Spain</span></a><select id="v16Language" aria-label="Language"><option value="en">🇬🇧 English</option><option value="es">🇪🇸 Español</option><option value="fr-BE">🇫🇷 Français</option><option value="de">🇩🇪 Deutsch</option><option value="nl">🇳🇱 Nederlands</option></select></header><a class="back" href="/#buy">'+esc(w[0])+'</a><div class="property-summary"><div><div class="place">'+esc([home.town,home.province].filter(Boolean).join(', '))+'</div><h1>'+esc(title)+'</h1>'+(reserved?'<p class="property-availability">'+esc(w[15])+'</p>':'')+'</div><div class="price">'+price()+'</div></div><div class="facts">'+facts.map(f=>'<span>'+esc(f)+'</span>').join('')+'</div>'+(images.length?'<section class="property-gallery" aria-label="'+esc(w[5])+'"><div class="v16-photo-stage"><img id="v16Photo" src="'+esc(images[photo])+'" alt="'+esc(title)+'" decoding="async"></div><div class="gallery-controls"><button id="v16Prev" type="button">'+w[3]+'</button><span id="v16PhotoCount" aria-live="polite"></span><button id="v16Next" type="button">'+w[4]+'</button></div><div class="property-thumbs">'+images.map((u,i)=>'<button type="button" data-photo="'+i+'" aria-label="'+w[5]+' '+(i+1)+'"><img src="'+esc(u)+'" alt="" loading="lazy"></button>').join('')+'</div></section>':'')+'<section class="card"><h2>'+w[1]+'</h2><p class="property-description">'+esc(description)+'</p>'+(id.startsWith('f5ef6f07')?'<p class="property-availability">'+w[25]+'</p>':'')+'</section>'+(concept&&images.length?'<section class="property-comparison"><h2>'+w[6]+'</h2><div class="before-after" style="--ba-split:100%"><img src="'+esc(images[0])+'" alt="'+w[7]+'"><div class="before-after__after"><img src="'+esc(concept)+'" alt="'+esc(w[9])+'" loading="lazy"></div><div class="before-after__divider" aria-hidden="true"></div><div class="before-after__labels"><span>'+w[7]+'</span><span>'+w[8]+'</span></div><input class="before-after__range" type="range" min="0" max="100" value="100" aria-label="'+w[8]+'" aria-describedby="v16AINote"></div><div class="v16-original-controls"><button type="button" data-split="100">'+w[7]+'</button><button type="button" data-split="50">'+w[8]+'</button></div><p id="v16AINote" class="before-after-note">'+w[9]+'</p></section>':'')+'<section class="card"><a class="back" href="/tell-us-what-you-are-looking-for.html?area='+encodeURIComponent(home.town||'')+'&lang='+lang+'">'+w[10]+'</a></section><div class="v16-cta"><strong class="price">'+price()+'</strong><a class="btn v16-enquire" href="'+esc(contactUrl())+'">'+w[2]+'</a></div>';
  document.getElementById('v16Language').value=lang;document.getElementById('v16Language').onchange=e=>{lang=e.target.value;try{localStorage.setItem('caveHomesLanguageManual',lang)}catch(_){}const u=new URL(location.href);u.searchParams.set('lang',lang);history.replaceState(null,'',u);render()};
  main.querySelector('.v16-enquire').onclick=()=>track('property_enquiry_start');
  if(images.length){gallery();document.getElementById('v16Prev').onclick=()=>{photo=Math.max(0,photo-1);gallery()};document.getElementById('v16Next').onclick=()=>{photo=Math.min(images.length-1,photo+1);gallery()};main.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>{photo=Number(b.dataset.photo);gallery()})}
  const range=main.querySelector('.before-after__range');if(range){const change=()=>{range.closest('.before-after').style.setProperty('--ba-split',range.value+'%');track('renovation_compare')};range.oninput=change;main.querySelectorAll('[data-split]').forEach(b=>b.onclick=()=>{range.value=b.dataset.split;change()})}
 }
 fetch('https://lesgzlhvrlxgtfuocadq.supabase.co/rest/v1/properties?id=eq.'+encodeURIComponent(id)+'&published=eq.true&select=*',{headers:{apikey:'sb_publishable_pPS6fORJPGFcGBIUPcxOxQ_1g4vazyg'}}).then(r=>{if(!r.ok)throw Error('Unavailable');return r.json()}).then(rows=>{if(!rows.length){main.innerHTML='<a class="back" href="/#buy">'+labels[lang][0]+'</a><section class="card"><h1>'+labels[lang][16]+'</h1></section>';return}home=rows[0];images=[...new Set([home.main_image_url,...(home.image_urls||[])].map(imageUrl).filter(Boolean))];render();track('property_view')}).catch(()=>{const p=document.createElement('p');p.textContent=labels[lang][17];main.prepend(p)});
})();
